"""initial schema

Revision ID: 89ae883a069e
Revises: 
Create Date: 2026-04-29 00:40:53.253860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89ae883a069e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date')
    )
    op.create_index('ix_price_history_ticker_date', 'price_history', ['ticker', sa.literal_column('date DESC')], unique=False)
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_return', sa.Double(), nullable=False),
    sa.Column('volatility', sa.Double(), nullable=False),
    sa.Column('sharpe_ratio', sa.Double(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_results_portfolio_id'), 'optimization_results', ['portfolio_id'], unique=False)
    op.create_table('portfolio_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'ticker')
    )
    op.create_index(op.f('ix_portfolio_assets_portfolio_id'), 'portfolio_assets', ['portfolio_id'], unique=False)
    op.create_table('risk_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('var_historical_95', sa.Double(), nullable=True),
    sa.Column('var_historical_99', sa.Double(), nullable=True),
    sa.Column('var_parametric_95', sa.Double(), nullable=True),
    sa.Column('var_parametric_99', sa.Double(), nullable=True),
    sa.Column('var_montecarlo_95', sa.Double(), nullable=True),
    sa.Column('var_montecarlo_99', sa.Double(), nullable=True),
    sa.Column('cvar_historical_95', sa.Double(), nullable=True),
    sa.Column('cvar_historical_99', sa.Double(), nullable=True),
    sa.Column('cvar_parametric_95', sa.Double(), nullable=True),
    sa.Column('cvar_parametric_99', sa.Double(), nullable=True),
    sa.Column('cvar_montecarlo_95', sa.Double(), nullable=True),
    sa.Column('cvar_montecarlo_99', sa.Double(), nullable=True),
    sa.Column('max_drawdown', sa.Double(), nullable=True),
    sa.Column('sharpe_ratio', sa.Double(), nullable=True),
    sa.Column('sortino_ratio', sa.Double(), nullable=True),
    sa.Column('beta', sa.Double(), nullable=True),
    sa.Column('annualised_return', sa.Double(), nullable=True),
    sa.Column('annualised_volatility', sa.Double(), nullable=True),
    sa.Column('correlation_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_metrics_portfolio_id'), 'risk_metrics', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_metrics_portfolio_id'), table_name='risk_metrics')
    op.drop_table('risk_metrics')
    op.drop_index(op.f('ix_portfolio_assets_portfolio_id'), table_name='portfolio_assets')
    op.drop_table('portfolio_assets')
    op.drop_index(op.f('ix_optimization_results_portfolio_id'), table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index('ix_price_history_ticker_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
